import './globals.css'
import SideBar from './components/SideBar'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({ children }) {
  return (
    <html lang='en'>
    <body className='flex'>
      <SideBar />
      <main className='ml-20 w-full'>{children}</main>


    </body>

    </html>
  )
}